### ISSUE TITLE
Advanced Balboa class is currently listed at 6:00PM (not 7:00PM)

### ISSUE THREAD

**Issue by kaitlingee** [NorthIsUp/shimmy.town#5]
Is this intentional?

<img width="485" alt="screen shot 2017-10-03 at 9 26 54 pm" src="https://user-images.githubusercontent.com/32504190/31159947-9d76fc04-a881-11e7-8434-ab7cff53f4e8.png">
(source: https://shimmy.town/classes/2017/October/advanced-balboa-dynamic-shape-and-rhythm/)

**Comment by NorthIsUp** [comment]
Nope! Thanks for catching this.


On October 3, 2017 at 9:28:41 PM, Kaitlin Gee (notifications@github.com)
wrote:

Is this intentional?

[image: screen shot 2017-10-03 at 9 26 54 pm]
<https://user-images.githubusercontent.com/32504190/31159947-9d76fc04-a881-11e7-8434-ab7cff53f4e8.png>
(source:
https://shimmy.town/classes/2017/October/advanced-balboa-dynamic-shape-and-rhythm/)


—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/NorthIsUp/shimmy.town/issues/5>, or mute the thread

**Comment by NorthIsUp** [comment]
fixed
